### ISSUE TITLE
Navionics REST APIs

### ISSUE THREAD

**Issue by qvanderlinden** [Navionics/webapi-community-examples#5]
Hi,

By browsing the documentation of your web api, I came across the following :

> All you need to start using Navionics is an access token: it's a short code that lets you use your Navionics account's capabilities. You can use the same access token with our interactive mapping libraries, React and JavaScript SDKs, and even **directly against our REST APIs**.

It is the last part I am most interested in. More precisely, I would like to request tiles directly via some URL instead of using the Leaflet/Google/etc. apis. Indeed, I am already using Mapbox GL JS for rendering my maps and I would really like to keep it that way.

Thanks in advance !

**Comment by qvanderlinden** [comment]
Do you have knowledge of any way to integrate with Mapbox-gl-js technology then ?

**Comment by bventurini** [comment]
Unfortunately, at the moment, integration with Mapbox-gl-js technology is not possible and there is no project to do it.

**Comment by qvanderlinden** [comment]
Ok, thank you for your replies

**Comment by bwicklund** [comment]
@bventurini --> Is integration with Mapbox-GL-JS still not available?

**Comment by steveneal** [comment]
Please provide mapbox integration.... :(((
