### ISSUE TITLE
API is giving 404

### ISSUE THREAD

**Issue by nicolocarpignoli** [Navionics/webapi-community-examples#6]
Hi,
I'm trying to use Navionics map over a Leaflet Map, but I have issues with API v2.

`Failed to load resource: the server responded with a status of 404 (Not Found)`

The Request URL is `https://tile1.navionics.io/tile/get_key/NAVIONICS_WEBAPI_P01/?_=1558962075534`

 Response is an HTML

```
<!DOCTYPE html><html><head><title></title><link rel="stylesheet" href="/stylesheets/style.css"></head><body><h1>Not Found</h1><h2></h2><pre></pre></body></html>
```

FYI the same issue happens on your example of Leaflet Integration. 
Same problems using another NavKey I got for email.

```
<!DOCTYPE html>
<html>
<head>
   <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>Navionics Web API v2</title>


    <!--Leaflet API-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.3/leaflet.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.3/leaflet.js"></script>

    <!-- jNavionicsChart -->
    <link rel="stylesheet" href="https://webapiv2.navionics.com/dist/webapi/webapi.min.css" >
    <script type="text/javascript" src="https://webapiv2.navionics.com/dist/webapi/webapi.min.no-dep.js"></script>
    <style>
        html, body {
            height: 100%;
            margin: 0px;
            padding: 0px
        }
        .map {
            width: 100%;
            height: 100%;
            min-height: 500px;
            border: 1px solid gray;
        }

    </style>
</head>
<body data-root="https://webapiv2.navionics.com/dist/webapi/images" >
<div id="nautical-map-container" class="map" ></div>
<script>
var map = L.map('nautical-map-container');

var overlay = new JNC.Leaflet.NavionicsOverlay({
    navKey: 'NAVIONICS_WEBAPI_P01',
    chartType: JNC.NAVIONICS_CHARTS.NAUTICAL,
    isTransparent: true,
    logoPayoff: true,
    zIndex: 1
});
map.setView([36.140751,-5.353585], 14);
overlay.addTo(map);

</script>
</body>
</html>
```

**Comment by bventurini** [comment]
Hi,
to use Navionics WebAPI you have to receive an proper key from Navionics,
from your example I see that you are not using a valid Navionics WebAPI key.
You have to fill the form you can find [here](https://www.navionics.com/fin/web-api/download).
I remind you that  WebAPI Navionics is a simple set of components that Navionics makes available to those who want to show Navionics viewer within their site concerning boating. It doesn’t work on localhost.
The service, besides being free and not requiring a registration, cannot be used for tracking boats or in a mobile app.

**Comment by nicolocarpignoli** [comment]
Hi, as I said in the post above, I used a NavKey I received on email, I just did not post it on the example because it is public.

My NavKey is something like 'Navionics_webapi_*****'.
I'm asking help because I tried the NavKey from the example and the NavKey I received and I saw the same error.

**Comment by bventurini** [comment]
Ok,
kindly write to apisupport@navionics.com the link to the page where you want to show Navionics maps so that we can directly check what is going wrong.

**Comment by nicolocarpignoli** [comment]
problem was the navkey is only working on the domains specified on the email used for requesting the key.
